"""add_audio_books_library_models

Revision ID: 80de24a1ee9e
Revises: 
Create Date: 2025-12-06 20:31:54.570557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80de24a1ee9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('first_publish_year', sa.Integer(), nullable=True),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_title'), 'works', ['title'], unique=False)
    op.create_table('editions',
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('isbn_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('publish_year', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=3), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editions_isbn'), 'editions', ['isbn'], unique=True)
    op.create_index(op.f('ix_editions_publish_year'), 'editions', ['publish_year'], unique=False)
    op.create_index(op.f('ix_editions_work_id'), 'editions', ['work_id'], unique=False)
    op.create_table('audio_books',
    sa.Column('edition_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_books_deleted_at'), 'audio_books', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_audio_books_edition_id'), 'audio_books', ['edition_id'], unique=False)
    op.create_index(op.f('ix_audio_books_status'), 'audio_books', ['status'], unique=False)
    op.create_table('book_providers',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_key', sa.String(length=200), nullable=False),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('work_id', sa.Uuid(), nullable=True),
    sa.Column('edition_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_key', name='uq_provider_external_key')
    )
    op.create_index('ix_book_providers_entity_lookup', 'book_providers', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_book_providers_provider'), 'book_providers', ['provider'], unique=False)
    op.create_table('chapters',
    sa.Column('audio_book_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=1000), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_book_id'], ['audio_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_book_id', 'chapter_number', name='uq_chapter_audio_book_number')
    )
    op.create_index(op.f('ix_chapters_audio_book_id'), 'chapters', ['audio_book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapters_audio_book_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_book_providers_provider'), table_name='book_providers')
    op.drop_index('ix_book_providers_entity_lookup', table_name='book_providers')
    op.drop_table('book_providers')
    op.drop_index(op.f('ix_audio_books_status'), table_name='audio_books')
    op.drop_index(op.f('ix_audio_books_edition_id'), table_name='audio_books')
    op.drop_index(op.f('ix_audio_books_deleted_at'), table_name='audio_books')
    op.drop_table('audio_books')
    op.drop_index(op.f('ix_editions_work_id'), table_name='editions')
    op.drop_index(op.f('ix_editions_publish_year'), table_name='editions')
    op.drop_index(op.f('ix_editions_isbn'), table_name='editions')
    op.drop_table('editions')
    op.drop_index(op.f('ix_works_title'), table_name='works')
    op.drop_table('works')
    # ### end Alembic commands ###
